config/routes.rb
Travel::Application.routes.draw do

  get "pictures/create"

  get "pictures/destroy"

  get "pictures/show"

  get "/registration" => "users#new", :as => :registration

  resources :users, only: ["create", "show"]

  resources :messages, only: ["new", "create", "destroy"]
  resources :chatboxes, only: ["show", "destrroy"]
  match "/conversations/:user_id" => "chatboxes#index", as: :conversations

  resources :places, :shallow => true do
    resources :comments
  end

  resources :sessions, only: ["new", "create", "destroy"]
  
  resources :pictures, :shallow => true do
    resources :comments
  end

   root :to => 'places#index'

end

app/models/place.rb
class Place < ActiveRecord::Base
  attr_accessible :description, :coords, :name, :ex_links_attributes, :temp, :user_id
  has_many :ex_links
  has_many :pictures, :dependent => :destroy
  has_many :comments, :as => :commentable, :dependent => :destroy
  belongs_to :user

  validates :description, :name, :presence => true
  validates :description, :length => {in: 10..1500}
  validates_associated :ex_links

  accepts_nested_attributes_for :ex_links, :allow_destroy => true
  accepts_nested_attributes_for :pictures, :allow_destroy => true

  before_save :set_default_values

  def set_default_values
    self.temp ||= false
    true
  end

end

app/controllers/places_controller.rb
class PlacesController < ApplicationController

 before_filter :redirect_to_login,    only: ['edit', 'update', 'destroy', 'new', 'create']
 before_filter(only: ['edit', 'update', 'destroy']) {|c| c.check_user_identity(Place)}  


  before_filter lambda { 
   session[:fake_place_id] ||= Place.create({name: "foo", description: "barfghfghgjgfhjgj", temp: true}).id 
   @fake_place_id = session[:fake_place_id]; 
          Rails.logger.info(@fake_place_id)
 }, :only => :create

 before_filter lambda { @fake_place_id = session[:fake_place_id] = nil }, :except => :create ##TODO destroy model

  # GET /places
  # GET /places.json
  def index
    if params[:user]
      @places = User.find(params[:user]).places.where(temp: false)
    else
      @places = Place.where(temp: false)
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @places }
    end
  end

  # GET /places/1
  # GET /places/1.json
  def show
    @place = Place.find(params[:id])
    # @pictures = @plcae.pictures
    # @comments = @plcae.comments

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @place }
    end
  end

  # GET /places/new
  # GET /places/new.json
  def new
    @place = Place.new
    @place.ex_links.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @place }
    end
  end

  # GET /places/1/edit
  def edit
      @place = Place.find(params[:id])
      @ex_links = @place.ex_links
      @pictures = @place.pictures
  end

  # POST /places
  # POST /places.json
  def create
   
      respond_to do |format|
        format.json do
          @pic = Place.find(@fake_place_id).pictures.create(pic: params[:place][:picture]) if params[:place][:picture]
          current_user.pictures << @pic 
          render json: @pic.to_json 
        end
        format.html do
          @place = current_user.places.build(params[:place].except(:picture))
          if @place.save
            Place.find(@fake_place_id).pictures.each { |pic| @place.pictures << pic }
            redirect_to action: "index", notice: 'Place was successfully created.'
          else
            flash.now[:alert] = @place.errors.full_messages.to_sentence words_connector: "\n" 
            render action: "new"
          end
        end
     end
  end

  # PUT /places/1
  # PUT /places/1.json
  def update

    @place = Place.find(params[:id])

    respond_to do |format|
        format.html do
          upd = @place.update_attributes(params[:place].except(:picture))
          if upd
            redirect_to places_path, notice: 'Place was successfully updated.'
          else
            flash[:alert] = @place.errors.full_messages #.to_sentence words_connector: "\n" 
            render action: "edit"
          end
        end
        format.json do
          pic = @place.pictures.create(pic: params[:place][:picture]) if params[:place][:picture]
          render json: pic.to_json 
        end
      end
  end

  # DELETE /places/1
  # DELETE /places/1.json
  def destroy
    @place = Place.find(params[:id])
    @place.destroy

    respond_to do |format|
      format.html { redirect_to places_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/places/_ex_link_fields.slim
.control-group
.controls.fields
  = f.text_field :link, :class => 'text_field required'
  = f.hidden_field :_destroy
  = link_to_function "remove", "", :class => 'js_delete'

app/views/places/_form.html.slim
= form_for @place, :html => { :class => "form-horizontal fileupload", :multipart => true } do |f|
  .control-group
    = f.label :name, :class => 'control-label'
    .controls
      = f.text_field :name, :class => 'text_field required', :style=>"display:block;clear:both;width:90%;"
    = f.label :description, :class => 'control-label '
    .controls
      = f.text_area :description, :class => 'text_area required', :style=>"display:block;clear:both;width:90%;"
      / div style="display:none;"
      = f.text_field :coords, :id => 'coords_data', :class => 'required', :style => "visibility:hidden;"
    / = link_to_add_fields "Add Extlink", f, :ex_links
    / - if params[:action] == 'edit'
    /   a id="restore_fields" style="display: none;" Restore
  .form-actions
    span class="btn btn-success fileinput-button" style="display:none;"
      = f.file_field :picture
      p 
    strong Set Location:
    .well#map_canvas style="width: 95%; height:300px;" coords=@place.try(:coords)
    = f.submit nil, :class => 'btn btn-primary', :value => "Done"
    '

  h2 Photos
  .control-group
    .dropzone
      .drop_caption Drop your photos here
      .progress.progress.progress-striped.active#pict_bar style="margin-top: 155px;display:none;"
         .bar.bar-success style="width: 100%;"

    ul.thumbnails
      li.span8
        - @place.pictures.each do |picture|
          = render partial: "shared/gallery", locals: { picture: picture }
          
#pic_template style="display:none;"
  div style="float:left;"
    a.boxclose.pic_delete_link pic_id="{{ id }}"
      div style="float:right" X
    a.thumbnail.added_pic href="{{ full_url }}" onclick="window.open(this.href);return false;"
      img src="{{ prev_url }}"
      img src='/images/ajax-loader.gif' style="display: none;"class="load_bar"

app/views/places/edit.html.slim
- model_class = Place
div class="page-header"
  h1=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human, :default => "Edit #{model_class.model_name.human}")
= render :partial => "form", :locals => {:pictures => @pictures}

app/views/places/index.html.slim
- model_class = Place
div class="page-header"
  h1 style="color: #E4E2CB;" Welcome to Travaler - 
  h4 style="margin-bottom:100px; color: #E4E2CB;" a place where you can sahre your impressions about places you visited
  small Please register if you want to be able to leave comments
  - @places.each do |place|
    h2= link_to place.name, place_path(place)
    div.well style="min-height:225px;"
      - unless place.pictures.blank?
        a href=picture_path(place.pictures.first)
          img style="display:block; float:left;margin:10px; margin-top:5px;"src=place.pictures[Random.rand(place.pictures.length)].pic(:medium)
      span style="padding:10px;" =place.description.length < 10 ? "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum." : place.description
      div style="width: 100%; margin-top: 10px;"
        - if current_user == place.user
          = link_to "Edit", edit_place_path(place), :class => 'btn btn-mini'
          = link_to "Destroy", place_path(place), :method => :delete, :data => { :confirm => "Are you sure?" }, :class => 'btn btn-mini btn-danger'

- if current_user
  = link_to t('.new', :default => t("helpers.links.new")), new_place_path, :class => 'btn btn-primary'

app/views/places/new.html.slim
- model_class = Place
div class="page-header"
  h1 style="margin-bottom:40px;" =t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human, :default => "New #{model_class.model_name.human}")
= render :partial => "form"

app/views/places/show.html.slim
- model_class = Place
div class="page-header"
  h1=t '.title', :default => @place.name

p
  strong= model_class.human_attribute_name(:description) + ':'
  br
  = @place.description
p
strong First Visior:
= link_to @place.user.displayed_name, user_path(@place.user)
p 
  strong Gallery:
  ul.thumbnails
    li.span8
      = render partial: "shared/gallery", collection: @place.pictures, as: :picture
p 
  strong Location:
  .well#map_canvas style="width: 95%; height:300px;" coords=@place.coords show="true"


.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), places_path, :class => 'btn'
  '
  - if (current_user == @place.user)
    = link_to t('.edit', :default => t("helpers.links.edit")), edit_place_path(@place), :class => 'btn'
    = link_to t('.destroy', :default => t("helpers.links.destroy")), place_path(@place), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'
  div 
    = render partial: "shared/comment", :collection => get_commentable.comments.reject(&:parent_id)
    = render partial: "shared/comment_form", locals: { commentable: get_commentable, parent_id: nil  }